### ISSUE TITLE
--host-resolver-rules command line flag working locally but fails on heroku

### ISSUE THREAD

**Issue by NemyaNation** [heroku/heroku-buildpack-google-chrome#112]
Can anyone help with this issue?

Running the following code locally:
```
require 'watir'
Watir.logger.level = :debug
args = [
    '--headless',
    '--no-sandbox',
    '--disable-dev-shm-usage',
    '--disable-gpu',
    '--remote-debugging-port=9222',
    '--host-resolver-rules=MAP google.com 192.0.2.1',
]
@browser = Watir::Browser.new :chrome, options: {args: args}

@browser.goto("https://www.google.com")
p @browser.html
```
Returns `<html><head></head><body></body></html>` as I would expect but on heroku it's actually returning the google.com source code.

Am I missing something?

Heroku Buildpacks installed:
```
https://github.com/heroku/heroku-buildpack-chromedriver
https://github.com/heroku/heroku-buildpack-google-chrome
```
Running with `Rails 6.1.3.1` and `ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]`

**Comment by dmcinnes** [comment]
Hello, this should be fixed by #40
