### ISSUE TITLE
Simply exiting....

### ISSUE THREAD

**Issue by wi-ski** [heroku/heroku-buildpack-google-chrome#15]
Hi there!

Im running this on Heroku and the process simply exits.  I've also read that `--headless` simply wont work until 59. :(

I believe its just segfaulting

**Comment by wi-ski** [comment]
And it was just working the other day :(

**Comment by rslifka** [comment]
@wi-ski So at one point it worked for you? It hasn't worked for me - sounds like our issues and suspicions are similar: https://github.com/heroku/heroku-buildpack-google-chrome/issues/17. Note that you can request 59 by setting the channel as mentioned in the README though that doesn't fix it.
