### ISSUE TITLE
How should the google chrome instance be started?

### ISSUE THREAD

**Issue by riston** [heroku/heroku-buildpack-google-chrome#2]
I am curious the google chrome headless uses still another port X to run the debugging protocol, is it allowed to use multiple ports inside Heroku instance? Example if I add node and chrome buildpack and install this https://github.com/cyrus-and/chrome-remote-interface module to drive the chrome, is it possible?

**Comment by wi-ski** [comment]
I would also like to know more about this. Currently getting `ECONNREFUSED` errors when trying to connect the node.js interface.  Anyone know how to do "things" with this?

**Comment by joshwlewis** [comment]
@riston you can still specify command-line arguments, so you could specify the debugging port like this: `google-chrome-beta --remote-debugging-port=9222`. Does that answer the question?

**Comment by joshwlewis** [comment]
@wi-ski that same argument might resolve the issue for you.

**Comment by joshwlewis** [comment]
`--remote-debugging-port` is now added by the shim, so this should no longer be an issue.

**Comment by wi-ski** [comment]
Yea - but it hard codes it?  Doesnt heroku expose ports dynamically?? :(

**Comment by LucianoGanga** [comment]
@joshwlewis , I get ECONNREFUSED errors too, but I can't use a fixed port. I need to run multiple instances dynamically. 

Do I have to add a special setting in the Procfile or something?

Thanks!
Luciano

**Comment by wi-ski** [comment]
I got around my issues by simply listening to @joshwlewis. @LucianoGanga - I would try using different tabs if you "need" multiple instances.
