### ISSUE TITLE
what's the size of /dev/shm in hoppy & free plan?

### ISSUE THREAD

**Issue by hbakhtiyor** [heroku/heroku-buildpack-google-chrome#21]

**Comment by deioo** [comment]
The build with Node.js and Chrome is around 230M, so under the 500 avaiable for both the hoppy and free plans.

**Comment by gunnarblom** [comment]
@hbakhtiyor  My hobby plan dyno has 64MB /dev/shm. This is too low for chrome, but in v65 you can use /tmp instead

@deioo is probably talking about compressed slug size.
