### ISSUE TITLE
“Cannot connect to browser: { Error: connect ECONNREFUSED 127.0.0.1:9222 ...”

### ISSUE THREAD

**Issue by tomsoderlund** [heroku/heroku-buildpack-google-chrome#28]
Possibly same/related to issue #2, but how do I actually start Chrome on Heroku?

My buildpacks:

	1. https://github.com/heroku/heroku-buildpack-google-chrome
	2. heroku/nodejs

My Procfile:

	web: node app/server.js

In runtime, I get this error:

	Cannot connect to browser: { Error: connect ECONNREFUSED 127.0.0.1:9222 
	    at Object.exports._errnoException (util.js:1020:11) 
	    at exports._exceptionWithHostPort (util.js:1043:20) 
	    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14) 
	  code: 'ECONNREFUSED', 
	  errno: 'ECONNREFUSED', 
	  syscall: 'connect', 
	  address: '127.0.0.1', 
	  port: 9222 }

**Comment by tomsoderlund** [comment]
I'm experimenting wildly now, tried changing Procfile to:

	web: /app/.apt/usr/bin/google-chrome & node app/server.js

From the Heroku log:

	heroku/web.1: Starting process with command `/app/.apt/usr/bin/google-chrome & node app/server.js` 
	app/web.1: /app/.apt/opt/google/chrome/chrome: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

Some issue with `libgconf-2` maybe?

**Comment by apellerano-pw** [comment]
I'm also seeing the `libgconf-2` error suddenly today. We haven't changed anything, chrome just stopped working on dynos

**Comment by apellerano-pw** [comment]
I've been hacking at it to work around whatever the issue is. By replicating what this buildpack does manually in our own slug compilation step I was able to kick the can down the road a little to another dependency issue with `libgtk-3-0` but haven't found a solution to that yet...

Here's what I added to our compile script to at least make the `libgconf-2` error go away, but no solution for `libgtk-3-0` yet that follows.

```bash
CACHE_DIR=$2
APT_CACHE_DIR="$CACHE_DIR/apt/cache"
APT_STATE_DIR="$CACHE_DIR/apt/state"
APT_OPTIONS="-o debug::nolocking=true -o dir::cache=$APT_CACHE_DIR -o dir::state=$APT_STATE_DIR"
apt-get $APT_OPTIONS -y --force-yes -d install --reinstall gconf2
```

**Comment by tomsoderlund** [comment]
I upgraded the stack from Cedar-14 to Heroku-16 and that fixed it for me.

So my current working settings are:

Stack: Heroku-16

Buildpacks:

	1. https://github.com/heroku/heroku-buildpack-google-chrome
	2. heroku/nodejs

Procfile:

	web: /app/.apt/usr/bin/google-chrome & node app/server.js

**Comment by apellerano-pw** [comment]
Thanks! I'm cautious about upgrading our stack atm but going off this I can manually install the pkg diff this buildpack does btwn the two stacks.

**Comment by apellerano-pw** [comment]
Yeah, I just installed everything the Heroku-16 stack installs and it works :dancing_men: 

Not sure what the actual subset of them I need is, but it's working sooooo...

```bash
CACHE_DIR=$2
APT_CACHE_DIR="$CACHE_DIR/apt/cache"
APT_STATE_DIR="$CACHE_DIR/apt/state"
APT_OPTIONS="-o debug::nolocking=true -o dir::cache=$APT_CACHE_DIR -o dir::state=$APT_STATE_DIR"
PACKAGES="libxss1 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxtst6 libnss3 libgconf-2-4 libxrandr2 libasound2 libatk1.0-0 libgtk2.0-0 libgtk-3-0 libxinerama1 libcairo-gobject2"
for PACKAGE in $PACKAGES; do
apt-get $APT_OPTIONS -y --force-yes -d install --reinstall $PACKAGE
done
```

**Comment by tomsoderlund** [comment]
Cool @apellerano-pw! Just curious, your compile script, is that a shell (.sh) script you run with [`postinstall`](https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process)?

**Comment by apellerano-pw** [comment]
Forgive me for I am a lowly client dev playing infrastructure for the day, but we use some other buildpack that allows for buildpacks inside buildpacks :D

https://github.com/kr/heroku-buildpack-inline

**Comment by tomsoderlund** [comment]
Thanks @apellerano-pw! I’m very new to this buildpacks stuff too. Just mashing buttons and hoping for the best (this app is not in production, yet).

**Comment by tomsoderlund** [comment]
I guess we can close this for now.
