### ISSUE TITLE
Selenium::WebDriver::Error::WebDriverError: unable to connect to chromedriver 127.0.0.1:9515

### ISSUE THREAD

**Issue by jamintz** [heroku/heroku-buildpack-google-chrome#32]
Trying to run this on Heroku – I've installed this buildpack and this one as well. I set my driver_path like `Selenium::WebDriver::Chrome.driver_path=ENV['GOOGLE_CHROME_BIN']
=> "/app/.apt/opt/google/chrome/chrome"
` but when I run `Watir::Browser.new :chrome` or `Watir::Browser.new :chrome, headless:true` I still get `Selenium::WebDriver::Error::WebDriverError: unable to connect to chromedriver 127.0.0.1:9515
`

Any ideas?

**Comment by AleksanderSzyszka** [comment]
+1... Did you find solution?

**Comment by jamintz** [comment]
I did, look at the code here as an example: https://github.com/jormon/minimal-chrome-on-heroku
