### ISSUE TITLE
GOOGLE_CHROME_SHIM has incorrect value

### ISSUE THREAD

**Issue by mpvosseller** [heroku/heroku-buildpack-google-chrome#33]
For me the `GOOGLE_CHROME_SHIM` environment variable is getting set to a value like:
```
/tmp/build_de6fa5a6488b4261bbdc4e5554cfade5/MyApp-11eaebf16d3943fcaf65af826a86856b6d3943fc/.apt/usr/bin/google-chrome-stable
```
instead of:
```
/app/.apt/usr/bin/google-chrome-stable
```

`GOOGLE_CHROME_BIN` is set correctly though. Here are both:
```
~ $ printenv | grep CHROME
GOOGLE_CHROME_BIN=/app/.apt/opt/google/chrome/chrome
GOOGLE_CHROME_SHIM=/tmp/build_de6fa5a6488b4261bbdc4e5554cfade5/MyApp-11eaebf16d3943fcaf65af826a86856b6d3943fc/.apt/usr/bin/google-chrome-stable
```

I have the following build packs installed:

```
https://github.com/emk/heroku-buildpack-rust
https://github.com/heroku/heroku-buildpack-google-chrome
https://github.com/heroku/heroku-buildpack-chromedriver
https://github.com/HashNuke/heroku-buildpack-elixir
```

Noticed a similar issue here: https://github.com/heroku/heroku-buildpack-xvfb-google-chrome/issues/5

**Comment by jmondo** [comment]
same issue 👍

**Comment by mpvosseller** [comment]
FWIW my workaround is to check if the environment variable `GOOGLE_CHROME_SHIM` is set and if it is I ignore the value and just use the hardcoded path `/app/.apt/usr/bin/google-chrome-stable`

**Comment by joshwlewis** [comment]
Sorry for the trouble here. I brought in https://github.com/heroku/heroku-buildpack-google-chrome/pull/27, which I think should solve the issue for you. Let me know if you disagree.

**Comment by mpvosseller** [comment]
It works! Thank you.
