### ISSUE TITLE
Support RHEL stack

### ISSUE THREAD

**Issue by bfrost2893** [heroku/heroku-buildpack-google-chrome#36]
We would like to use RHEL as our stack, which means we can't use this buildpack. Could we add some conditions for running the buildpack using RHEL compliant commands?

**Comment by edmorley** [comment]
Hi! Heroku's stacks are all based on Ubuntu. If you're using RHEL via the Heroku container stack, you're probably better off installing Chrome manually in the Dockerfile (or using one of the Chrome/Selenium docker images that are available). Or is this for use with another hosting provider? :-)
