### ISSUE TITLE
Add precompiled binary to buildpack

### ISSUE THREAD

**Issue by dleavitt** [heroku/heroku-buildpack-google-chrome#47]
Unless I'm doing it pretty wrong, it seems that adding this buildpack substantially increases deploy times because chrome and its deps have to get downloaded every deploy.

Does it make sense/is it feasible to precompile all the relevant binaries and include them in the buildpack? This is what the [nginx buildpack](https://github.com/beanieboi/nginx-buildpack) does.

**Comment by joshwlewis** [comment]
Yes, there is definitely additional resource usage to download each time. We are hesitant to provide the binaries directly though, mostly due to the rather fast-paced release cycle of Chrome and the plethora of binaries required to run it.
