### ISSUE TITLE
Not compatible with heroku-18

### ISSUE THREAD

**Issue by tillkruss** [heroku/heroku-buildpack-google-chrome#50]
We'd like to upgrade from `heroku-16` to `heroku-18`, but our test suite depends on this buildpack. Any change this buildpack could be made compatible?

```
STACK must be 'cedar-14' or 'heroku-16', not 'heroku-18.'
```

**Comment by stereoscott** [comment]
FWIF, We just ran into this today, too. We don't have an urgent need to use the new stack, but one idea might be to fork this repo and update the line to include `heroku-18` and try with the same dependencies as heroku-16: https://github.com/heroku/heroku-buildpack-google-chrome/blob/master/bin/compile#L68

**Comment by transoceanic2000** [comment]
Was this not fixed for you by #54 ?

**Comment by edmorley** [comment]
Closing this as fixed by #54 (which merged after this issue was opened) :-)
