### ISSUE TITLE
Karma-chrome-launcher failed to launch chrome Headless

### ISSUE THREAD

**Issue by kuldeepk7321** [heroku/heroku-buildpack-google-chrome#53]
Hi, I am trying to run tests for my application on Chrome Headless on Jenkins. To achieve this I am using https://github.com/heroku/heroku-buildpack-google-chrome/ buildpack but after using this buildpack karma-chrome-launcher failed to even respond back which earlier was failing to start chrome headless.

I am adding the screenshot of the console -
with https://github.com/heroku/heroku-buildpack-google-chrome/ buildpack
![buildpack issue](https://user-images.githubusercontent.com/22715250/44448591-4d80c000-a609-11e8-896c-f4cac46e011e.JPG)

without https://github.com/heroku/heroku-buildpack-google-chrome/ buildpack
![buildpack issue--2](https://user-images.githubusercontent.com/22715250/44450720-35ac3a80-a60f-11e8-8de4-e0c15c170f9c.JPG)

I am using puppetee for launching chrome headless ..Following is the karma configuration snippet-

`var puppetteer = require('puppeteer');`

`process.env.CHROME_BIN = puppetteer.executablePath();`
 `configuration.plugins.push(require('karma-chrome-launcher'));`

  `configuration.browsers = ['ChromeHeadlessNoSandbox'];`
 ` configuration.customLaunchers = {`
    `ChromeHeadlessNoSandbox: {`
      `base: 'ChromeHeadless',`
      `flags: ['--no-sandbox'],`
  `  },`
`  };`

**Comment by mobilutz** [comment]
@kuldeepk7321 Did you find a way of using Chrome with karma?

**Comment by edmorley** [comment]
Hi @kuldeepk7321, did you get this figured out in the end? :-)

**Comment by kuldeepk7321** [comment]
Yes.. i don't remember what i did then... But yes i figured it out.

**Comment by edmorley** [comment]
Great :-)
