### ISSUE TITLE
Chrome not reachable

### ISSUE THREAD

**Issue by mjsommer** [heroku/heroku-buildpack-google-chrome#63]
@abrown85 - I am creating a new issue, to try to bring it into focus. If we resolve this, I will close out my other comments on #56 and #59.

Environment:
`Heroku, Stack 16`
`ruby 2.4.4p296`
`Rails 4.2.10`

Environment
`production' (app, vs testing)

Gems
`gem 'capybara'`
`gem 'capybara-selenium'`

Buildpacks:
heroku/ruby
https://github.com/heroku/heroku-buildpack-chromedriver
https://github.com/heroku/heroku-buildpack-google-chrome

Code (Ruby console):
`irb(main):001:0> Capybara.current_session.visit('http://yahoo.com')`
`irb(main):001:0> Capybara.current_session.find('#some_element')`

Error:
`Selenium::WebDriver::Error::WebDriverError: chrome not reachable
  (Session info: headless chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.4.0-1027-aws x86_64)
	from /app/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
	from /app/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
	from /app/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
	from /app/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from /app/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
	from /app/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from /app/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/oss/bridge.rb:584:in `execute'
	from /app/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/oss/bridge.rb:562:in `find_elements_by'
	from /app/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/search_context.rb:78:in `find_elements'
	from /app/vendor/bundle/ruby/2.4.0/gems/capybara-3.7.2/lib/capybara/selenium/driver.rb:76:in `find_css'
	from /app/vendor/bundle/ruby/2.4.0/gems/capybara-3.7.2/lib/capybara/node/base.rb:98:in `find_css'
	from /app/vendor/bundle/ruby/2.4.0/gems/capybara-3.7.2/lib/capybara/queries/selector_query.rb:137:in `find_nodes_by_selector_format'
	from /app/vendor/bundle/ruby/2.4.0/gems/capybara-3.7.2/lib/capybara/queries/selector_query.rb:102:in `block in resolve_for'
	from /app/vendor/bundle/ruby/2.4.0/gems/capybara-3.7.2/lib/capybara/node/base.rb:77:in `synchronize'
	from /app/vendor/bundle/ruby/2.4.0/gems/capybara-3.7.2/lib/capybara/queries/selector_query.rb:101:in `resolve_for'
	from /app/vendor/bundle/ruby/2.4.0/gems/capybara-3.7.2/lib/capybara/node/finders.rb:288:in `block in synced_resolve'
	from /app/vendor/bundle/ruby/2.4.0/gems/capybara-3.7.2/lib/capybara/node/base.rb:82:in `synchronize'
	from /app/vendor/bundle/ruby/2.4.0/gems/capybara-3.7.2/lib/capybara/node/finders.rb:286:in `synced_resolve'
	from /app/vendor/bundle/ruby/2.4.0/gems/capybara-3.7.2/lib/capybara/node/finders.rb:33:in `find'
	from /app/vendor/bundle/ruby/2.4.0/gems/capybara-3.7.2/lib/capybara/session.rb:728:in `block (2 levels) in <class:Session>'
	from (irb):2
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/commands/console.rb:110:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	from /app/bin/rails:9:in `require'
	from /app/bin/rails:9:in `<main>'
irb(main):003:0> `

This code is running perfectly in Mac OSX, but I have not been able to deploy it to Heroku.

Please let me know your thoughts.

Thanks again,
Martin

**Comment by jabrown85** [comment]
Can you post your capybara initialization code? Also, what happens if you just `heroku run bash` into the app and run `$GOOGLE_CHROME_SHIM`?

**Comment by jabrown85** [comment]
Just to give you an idea of what is working for me

```
Capybara.app = App

chrome_bin = ENV.fetch('GOOGLE_CHROME_SHIM', nil)
chrome_opts = chrome_bin ? { "chromeOptions" => { "binary" => chrome_bin } } : {}

Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(
     app,
     browser: :chrome,
     desired_capabilities: Selenium::WebDriver::Remote::Capabilities.chrome(chrome_opts)
  )
end
```

**Comment by mjsommer** [comment]
@ jabrown85

> what happens if you just heroku run bash into the app and run $GOOGLE_CHROME_SHIM?

`Running bash on ⬢ <myHerokuApp> ... up, run.1909 (Free)
~ $ $GOOGLE_CHROME_SHIM
[0924/192338.160924:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9222/devtools/browser/8ddf449e-5ec1-496e-ad36-62a4cc2e6326`

**Comment by jabrown85** [comment]
That's good. That means chrome is starting up fine. Is the capybara configuration you have look similar to the one above? You should probably be using `ENV.fetch('GOOGLE_CHROME_SHIM, nil)` if you aren't already. If you are missing any of the flags we pass in, it would be exiting early or crashing on startup.

**Comment by mjsommer** [comment]
@ jabrown85, thank you for encouraging me to dig into the Capybara config. My configuration looks similar to yours, with the exception that I configure Capybara after registering it, using the following:

`Capybara.configure do |config|`
`  config.run_server = false`
`  config.default_driver = :chrome`
`  config.javascript_driver = :chrome`
`  config.app_host = 'https://www.example.com'`
`end`

In reading the [docs](https://github.com/teamcapybara/capybara#drivers), it states "... if you'd prefer to run everything in Selenium, you could do:"

`Capybara.default_driver = :selenium # :selenium_chrome and :selenium_chrome_headless are also registered`

I changed my code to read as follows, and I am up and running:

`  config.default_driver = :selenium_chrome_headless`
`  config.javascript_driver = :selenium_chrome_headless`

Thanks again!!

**Comment by jamintz** [comment]
@jabrown85 when I run $GOOGLE_CHROME_SHIM in Heroku (16) bash I see:
/app/.apt/opt/google/chrome/chrome: symbol lookup error: /app/.apt/usr/lib/x86_64-linux-gnu/libatk-1.0.so.0: undefined symbol: g_log_structured_standard

Do you know what the issue could be there?

**Comment by jabrown85** [comment]
@jamintz try clearing your cache. If it's a CI run, just use the "Run again without cache". If it's not for CI, you can try this https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache.

**Comment by jabrown85** [comment]
@jamintz try clearing your cache. If it's a CI run, just use the "Run again without cache". If it's not for CI, you can try this https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache.

**Comment by jamintz** [comment]
That worked! Thank you!

**Comment by franzejr** [comment]
I am having the same error and cleaning up the cache didn't solve it ? :/

```
/app/.apt/opt/google/chrome/chrome: symbol lookup error: /app/.apt/usr/lib/x86_64-linux-gnu/libatk-1.0.so.0: undefined symbol: g_log_structured_standard
```

Any thoughts?
