### ISSUE TITLE
Where do I find the user data directory?

### ISSUE THREAD

**Issue by corey2** [heroku/heroku-buildpack-google-chrome#69]
The webpage at https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md says that the user data directory is supposed to be ~/.config, but when I do Heroku run bash from the command line interface and try to go to that directory, it says the directory doesn't exist. Is there some other way that I can have a specific google user profile be included on an instance of Heroku that has Google Chrome?

**Comment by joshwlewis** [comment]
On a Heroku dyno, `~` will resolve to `/app`. We don't do anything to create a `/app/.config` directory for you. If that's something you want, you'd have to do that yourself either at runtime, or with a custom buildpack.
