### ISSUE TITLE
google-chrome no longer running

### ISSUE THREAD

**Issue by Steven4294** [heroku/heroku-buildpack-google-chrome#84]
```
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.                                    
  (unknown error: DevToolsActivePort file doesn't exist)                                                                                             
  (The process started from chrome location /app/.apt/usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed
.)       
```

Getting the above error in my python script. Have been running the same script for the past year or so, so I'm guessing something updated with Chrome but that wasn't updated in this buildpack.

<img width="823" alt="Screen Shot 2020-04-08 at 2 40 35 AM" src="https://user-images.githubusercontent.com/8051383/78752622-66ef9080-7942-11ea-9cdb-f325de8ad60a.png">

*Note I would have received a different error if there were a mismatch between the chromedriver version and the version of chrome. E.g. (when running locally to force the error): 

```
Message: session not created: This version of ChromeDriver only supports Chrome version 78
```

and my previously working python code:

```
options = webdriver.ChromeOptions()
options.binary_location = os.environ.get("GOOGLE_CRHOME_BIN")
options.add_argument("--no-sandbox")
options.add_argument("--headless")
options.add_argument("--disable-dev-shm-usage")
options.add_argument('--disable-gpu')

the_path = os.environ.get("CHROMEDRIVER_PATH")
driver = webdriver.Chrome(executable_path=the_path, options=options)
```

**Comment by beauraF** [comment]
I've had the same worries for over 8 hours. On every application I deploy. The issue is: 

```
/app/.apt/opt/google/chrome/chrome: error while loading shared libraries: libxcb-dri3.so.0: cannot open shared object file: No such file or directory
```

Seems they changed something in the base image?

**Comment by Steven4294** [comment]
Awesome @beauraF you're a lifesaver. I'm heading to bed now but I'll be up 8 hours from now to follow up on this. Definitely a critical issue for us.

**Comment by beauraF** [comment]
Have a good night Steven, hope it will be merge in the meantime. :)
https://github.com/heroku/heroku-buildpack-google-chrome/pull/85
